name = "Blueberry"
author = "Seth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b4b1c08f4f71cb0ce2ef1dbe463496563621bf7a008db0379f90c102759766b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
