name = "Blueberry"
author = "Seth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fcd90054c434e8ced603d22a5316611859edc4baf0bd8896f98f87b581d3c1b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.1"]
