name = "Blueberry"
author = "Seth"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b97e810f3ccfbd8195a55e8618df5f7675f6742068c098081778e92e23484e03"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
