#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Mar 18 16:33:42 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=MakeUp-UltraFast-9.4c.zip
